language: python

services:
    - redis
    - postgresql

install: bash bin/travis-build.bash
script: bash bin/travis-run.bash

dist: focal

stages:
  - Tests

jobs:
  include:
    - stage: Tests
      python: "2.7"
      env: CKANVERSION=master
    - python: "3.6"
      env: CKANVERSION=master

cache:
  directories:
    - $HOME/.cache/pip
